# Generated by Django 5.1.7 on 2025-03-21 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codegen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecthistory',
            name='project_path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
