# Generated by Django 4.2 on 2025-04-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codegen', '0002_projecthistory_project_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecthistory',
            name='project_name',
            field=models.CharField(default='Unnamed Project', max_length=100),
            preserve_default=False,
        ),
    ]
